### ISSUE TITLE
GlobalStyle 적용 문제

### ISSUE THREAD

**Issue by soojjung** [seoltang/period-calculator#5]
GlobalStyle이 적용 안되어있길래 적용시켰더니 defaltPageInputs UI가 변경되었습니다.
(각 whitebox부분의 높이가 줄어듬)
그래서 GlobalStyle의 어떤 속성 때문인지를 파악하기위해 모든 코드를 주석처리하였는데
그래도 이상하게 보여서 다시 GlobalStyle 자체를 빼주었습니다..
GlobalStyle도 적용하면서 기존UI가 변경되지 않으려면 어떻게 해야할지 고민입니닷

**Comment by seoltang** [comment]
_* fixed_

GlobalStyle을 적용하면 reset이 적용되어서 태그에 기본으로 붙어있던 스타일들이 없어집니다.

- `<p>` 태그의 위아래 margin
- `<b>` 태그의 font-weight: bold
- line-height

reset으로 변경되는 해당 스타일들을 수정해주고 GlobalStyle을 적용하면 동일한 UI를 볼 수 있습니다.
